-- MySQL Script generated by MySQL Workbench
-- Thu 15 Nov 2018 11:55:47 WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema reservasiruangan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `ci_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ci_session` (
  `id` VARCHAR(40) NOT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `timestamp` INT(10) UNSIGNED NULL DEFAULT '0',
  `data` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_role` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(100) NULL DEFAULT NULL,
  `user_password` VARCHAR(255) NULL DEFAULT NULL,
  `user_full_name` VARCHAR(100) NULL DEFAULT NULL,
  `user_email` VARCHAR(100) NULL DEFAULT NULL,
  `user_phone` VARCHAR(45) NULL DEFAULT NULL,
  `user_role_role_id` INT(11) NULL DEFAULT NULL,
  `user_address` TEXT NULL DEFAULT NULL,
  `user_created_date` TIMESTAMP NULL DEFAULT NULL,
  `user_last_update` TIMESTAMP NULL DEFAULT NULL,
  `user_deleted` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_user_role_idx` (`user_role_role_id` ASC),
  CONSTRAINT `fk_user_user_role`
    FOREIGN KEY (`user_role_role_id`)
    REFERENCES `user_role` (`role_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `activity_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `activity_log` (
  `log_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `log_action` VARCHAR(255) NULL DEFAULT NULL,
  `log_module` VARCHAR(100) NULL DEFAULT NULL,
  `log_info` TEXT NULL DEFAULT NULL,
  `log_date` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`log_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `catalog_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catalog_category` (
  `catalog_category_id` INT NOT NULL AUTO_INCREMENT,
  `catalog_category_name` VARCHAR(100) NULL,
  `catalog_category_created_date` TIMESTAMP NULL,
  `catalog_category_last_update` TIMESTAMP NULL,
  `user_user_id` INT(11) NULL,
  PRIMARY KEY (`catalog_category_id`),
  INDEX `fk_catalog_category_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_catalog_category_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catalog` (
  `catalog_id` INT NOT NULL AUTO_INCREMENT,
  `catalog_sku` VARCHAR(16) NULL,
  `catalog_name` VARCHAR(255) NULL,
  `catalog_url_slug` VARCHAR(255) NULL,
  `catalog_category_slug` VARCHAR(70) NULL,
  `catalog_desc` TEXT NULL DEFAULT NULL,
  `catalog_image` VARCHAR(255) NULL,
  `catalog_for_rent` TINYINT(1) NULL DEFAULT NULL,
  `category_category_id` INT NULL,
  `catalog_created_date` TIMESTAMP NULL,
  `catalog_last_update` TIMESTAMP NULL,
  `user_user_id` INT(11) NULL,
  PRIMARY KEY (`catalog_id`),
  INDEX `fk_catalog_user1_idx` (`user_user_id` ASC),
  INDEX `fk_catalog_category1_idx` (`category_category_id` ASC),
  CONSTRAINT `fk_catalog_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_catalog_category1`
    FOREIGN KEY (`category_category_id`)
    REFERENCES `catalog_category` (`catalog_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customer_full_name` VARCHAR(255) NULL,
  `customer_email` VARCHAR(255) NULL,
  `customer_password` VARCHAR(255) NULL,
  `customer_phone` VARCHAR(100) NULL,
  `customer_address` TEXT NULL,
  `customer_created_date` TIMESTAMP NULL,
  `customer_last_update` TIMESTAMP NULL,
  `customer_token` VARCHAR(255) NULL,
  `customer_token_expired` TIMESTAMP NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mediamanager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamanager` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `isfile` TINYINT(1) NULL DEFAULT '0',
  `label` TEXT NULL DEFAULT NULL,
  `info` TEXT NULL DEFAULT NULL,
  `upload_at` DATETIME NULL DEFAULT NULL,
  `album_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mediamanager_album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mediamanager_album` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(255) NULL DEFAULT NULL,
  `upload_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mptt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mptt` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `lft` INT(11) NOT NULL DEFAULT '0',
  `rgt` INT(11) NOT NULL DEFAULT '0',
  `parent` INT(11) NOT NULL DEFAULT '0',
  `url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `page` (
  `page_id` INT(11) NOT NULL AUTO_INCREMENT,
  `page_name` VARCHAR(100) NULL DEFAULT NULL,
  `page_short_desc` VARCHAR(255) NULL DEFAULT NULL,
  `page_content` TEXT NULL DEFAULT NULL,
  `page_is_published` TINYINT(4) NULL DEFAULT '0',
  `page_image` VARCHAR(255) NULL DEFAULT NULL,
  `user_user_id` INT(11) NULL DEFAULT NULL,
  `page_created_date` TIMESTAMP NULL DEFAULT NULL,
  `page_last_update` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`page_id`),
  INDEX `fk_page_user1` (`user_user_id` ASC),
  CONSTRAINT `fk_page_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `setting_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setting_category` (
  `setting_category_id` INT NOT NULL AUTO_INCREMENT,
  `setting_category_name` VARCHAR(45) NULL,
  PRIMARY KEY (`setting_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `setting` (
  `setting_key` VARCHAR(255) NOT NULL,
  `setting_value` VARCHAR(255) NULL DEFAULT NULL,
  `setting_category_setting_category_id` INT NULL,
  PRIMARY KEY (`setting_key`),
  INDEX `fk_setting_setting_category1_idx` (`setting_category_setting_category_id` ASC),
  CONSTRAINT `fk_setting_setting_category1`
    FOREIGN KEY (`setting_category_setting_category_id`)
    REFERENCES `setting_category` (`setting_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `catalog_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catalog_image` (
  `catalog_image_id` INT NOT NULL AUTO_INCREMENT,
  `catalog_catalog_id` INT NULL,
  `catalog_image_path` VARCHAR(255) NULL,
  PRIMARY KEY (`catalog_image_id`),
  INDEX `fk_catalog_image_catalog1_idx` (`catalog_catalog_id` ASC),
  CONSTRAINT `fk_catalog_image_catalog1`
    FOREIGN KEY (`catalog_catalog_id`)
    REFERENCES `catalog` (`catalog_id`)
    ON DELETE CASCADE
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalog_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catalog_video` (
  `catalog_video_id` INT NOT NULL AUTO_INCREMENT,
  `catalog_catalog_id` INT NULL,
  `catalog_video_desc` TEXT NULL,
  `catalog_video_link` VARCHAR(255) NULL,
  PRIMARY KEY (`catalog_video_id`),
  INDEX `fk_catalog_video_catalog1_idx` (`catalog_catalog_id` ASC),
  CONSTRAINT `fk_catalog_video_catalog1`
    FOREIGN KEY (`catalog_catalog_id`)
    REFERENCES `catalog` (`catalog_id`)
    ON DELETE CASCADE
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posting_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posting_category` (
  `posting_category_id` INT NOT NULL AUTO_INCREMENT,
  `posting_category_name` VARCHAR(255) NULL,
  `posting_category_created_date` TIMESTAMP NULL,
  `posting_category_last_update` TIMESTAMP NULL,
  `user_user_id` INT(11) NULL,
  PRIMARY KEY (`posting_category_id`),
  INDEX `fk_posting_category_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_posting_category_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posting` (
  `posting_Id` INT NOT NULL AUTO_INCREMENT,
  `posting_title` VARCHAR(150) NULL,
  `posting_short_desc` VARCHAR(255) NULL,
  `posting_desc` TEXT NULL,
  `posting_image` VARCHAR(255) NULL,
  `posting_category_posting_category_id` INT NULL,
  `posting_publish_status` TINYINT(1) NULL DEFAULT 1,
  `posting_created_date` TIMESTAMP NULL,
  `posting_last_update` TIMESTAMP NULL,
  `user_user_id` INT(11) NULL,
  `posting_viewer` INT NULL DEFAULT 0,
  PRIMARY KEY (`posting_Id`),
  INDEX `fk_posting_posting_category1_idx` (`posting_category_posting_category_id` ASC),
  INDEX `fk_posting_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_posting_posting_category1`
    FOREIGN KEY (`posting_category_posting_category_id`)
    REFERENCES `posting_category` (`posting_category_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_posting_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banner` (
  `banner_id` INT NOT NULL AUTO_INCREMENT,
  `banner_title` VARCHAR(255) NULL,
  `banner_desc` TEXT NULL,
  `banner_image` VARCHAR(255) NULL,
  `banner_created_date` TIMESTAMP NULL,
  `banner_last_update` TIMESTAMP NULL,
  `user_user_id` INT(11) NULL,
  PRIMARY KEY (`banner_id`),
  INDEX `fk_banner_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_banner_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservasi_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservasi_status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservasi_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservasi_position` (
  `position_id` INT NOT NULL AUTO_INCREMENT,
  `position_name` VARCHAR(45) NULL,
  PRIMARY KEY (`position_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservasi` (
  `reservasi_id` INT NOT NULL AUTO_INCREMENT,
  `reservasi_type` VARCHAR(255) NULL,
  `reservasi_date_start` DATE NULL,
  `reservasi_date_end` DATE NULL,
  `reservasi_attendance` INT NULL,
  `reservasi_other_request` TEXT NULL,
  `reservasi_request_file` VARCHAR(255) NULL,
  `reservasi_proposal_file` VARCHAR(255) NULL,
  `catalog_catalog_id` INT NULL,
  `customer_customer_id` INT NULL,
  `reservasi_created_at` TIMESTAMP NULL,
  `reservasi_updated_at` TIMESTAMP NULL,
  `reservasi_status_status_id` INT NULL,
  `reservasi_position_position_id` INT NULL,
  `reservasi_response_file` VARCHAR(255) NULL,
  `reservasi_end_message` TEXT NULL,
  `reservasi_is_complete` TINYINT(1) NULL DEFAULT 0,
  `reservasi_is_deleted` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`reservasi_id`),
  INDEX `fk_reservasi_catalog1_idx` (`catalog_catalog_id` ASC),
  INDEX `fk_reservasi_customer1_idx` (`customer_customer_id` ASC),
  INDEX `fk_reservasi_reservasi_status1_idx` (`reservasi_status_status_id` ASC),
  INDEX `fk_reservasi_reservasi_position1_idx` (`reservasi_position_position_id` ASC),
  CONSTRAINT `fk_reservasi_catalog1`
    FOREIGN KEY (`catalog_catalog_id`)
    REFERENCES `catalog` (`catalog_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservasi_customer1`
    FOREIGN KEY (`customer_customer_id`)
    REFERENCES `customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservasi_reservasi_status1`
    FOREIGN KEY (`reservasi_status_status_id`)
    REFERENCES `reservasi_status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservasi_reservasi_position1`
    FOREIGN KEY (`reservasi_position_position_id`)
    REFERENCES `reservasi_position` (`position_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservasi_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reservasi_log` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `log_message` TEXT NULL,
  `reservasi_reservasi_id` INT NULL,
  `from_user_id` INT(11) NULL,
  `reservasi_status_status_id` INT NULL,
  `log_date` TIMESTAMP NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_reservasi_log_reservasi1_idx` (`reservasi_reservasi_id` ASC),
  INDEX `fk_reservasi_log_user1_idx` (`from_user_id` ASC),
  INDEX `fk_reservasi_log_reservasi_status1_idx` (`reservasi_status_status_id` ASC),
  CONSTRAINT `fk_reservasi_log_reservasi1`
    FOREIGN KEY (`reservasi_reservasi_id`)
    REFERENCES `reservasi` (`reservasi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservasi_log_user1`
    FOREIGN KEY (`from_user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservasi_log_reservasi_status1`
    FOREIGN KEY (`reservasi_status_status_id`)
    REFERENCES `reservasi_status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sliders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sliders` (
  `slider_id` INT NOT NULL AUTO_INCREMENT,
  `slider_caption` VARCHAR(255) NULL,
  `slider_photo` VARCHAR(255) NULL,
  PRIMARY KEY (`slider_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
